// Writes src/environments/environment.prod.ts from the STYTCH_PUBLIC_TOKEN env
// var so production bundles carry the deploy's public token. The token is
// public (safe to ship to browsers); this keeps it out of committed source.
// angular.json swaps environment.ts -> environment.prod.ts for production.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const token = process.env.STYTCH_PUBLIC_TOKEN ?? '';
const out = join(dirname(fileURLToPath(import.meta.url)), '../src/environments/environment.prod.ts');

writeFileSync(
  out,
  `// Generated by scripts/inject-stytch.mjs from STYTCH_PUBLIC_TOKEN. Do not commit.\n` +
    `export const environment = {\n` +
    `  production: true,\n` +
    `  apiBaseUrl: '',\n` +
    `  stytchPublicToken: ${JSON.stringify(token)},\n` +
    `};\n`,
);

console.log(token ? 'inject-stytch: token set from STYTCH_PUBLIC_TOKEN' : 'inject-stytch: no token, stub mode');
