packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: false
  msgpackr-extract: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lmdb
  - msgpackr-extract
